package com.wenjun.recsys.dao;

import com.wenjun.recsys.model.RecommendModel;
import org.springframework.stereotype.Repository;

@Repository
public interface RecommendModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu Jan 23 12:57:48 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu Jan 23 12:57:48 CST 2020
     */
    int insert(RecommendModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu Jan 23 12:57:48 CST 2020
     */
    int insertSelective(RecommendModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu Jan 23 12:57:48 CST 2020
     */
    RecommendModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu Jan 23 12:57:48 CST 2020
     */
    int updateByPrimaryKeySelective(RecommendModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Thu Jan 23 12:57:48 CST 2020
     */
    int updateByPrimaryKey(RecommendModel record);
}